"""empty message

Revision ID: 430d93a5820a
Revises: 23bed313e256
Create Date: 2023-02-25 22:09:30.727594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430d93a5820a'
down_revision = '23bed313e256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
